# Generated by Django 6.0.3 on 2026-03-27 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=64)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('browser', models.CharField(blank=True, max_length=128)),
                ('os', models.CharField(blank=True, max_length=128)),
                ('device', models.CharField(blank=True, max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='TrackingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_session_id', models.CharField(blank=True, max_length=64)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity_at', models.DateTimeField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_sessions', to='core.project')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_sessions', to='analytics.visitor')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('pageview', 'Pageview'), ('click', 'Click')], max_length=32)),
                ('url', models.TextField()),
                ('title', models.CharField(blank=True, max_length=512)),
                ('referrer', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField()),
                ('screen_width', models.PositiveIntegerField(blank=True, null=True)),
                ('screen_height', models.PositiveIntegerField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=32)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.project')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='analytics.trackingsession')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='analytics.visitor')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.AddIndex(
            model_name='visitor',
            index=models.Index(fields=['project', 'client_id'], name='analytics_v_project_9ec229_idx'),
        ),
        migrations.AddConstraint(
            model_name='visitor',
            constraint=models.UniqueConstraint(fields=('project', 'client_id'), name='unique_visitor_per_project'),
        ),
        migrations.AddIndex(
            model_name='trackingsession',
            index=models.Index(fields=['project', 'visitor', '-last_activity_at'], name='analytics_t_project_e4ea8e_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['project', 'occurred_at'], name='analytics_e_project_a1edb4_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['session', 'event_type'], name='analytics_e_session_1f7d25_idx'),
        ),
    ]
