# Generated by Django 6.0.3 on 2026-03-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='author',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='campaign',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='content_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='event',
            name='content_slug',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='content_title',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='event',
            name='cta_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='destination_url',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='engaged_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='event',
            name='medium',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='page_type',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='event',
            name='properties',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='event',
            name='scroll_percent',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='source_group',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='event',
            name='source_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='event',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='utm_content',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='utm_medium',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='utm_source',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='utm_term',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='trackingsession',
            name='campaign',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='trackingsession',
            name='landing_category',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='trackingsession',
            name='landing_page_type',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='trackingsession',
            name='landing_title',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='trackingsession',
            name='landing_url',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trackingsession',
            name='medium',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='trackingsession',
            name='referrer_domain',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='trackingsession',
            name='source_group',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='trackingsession',
            name='source_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='visitor',
            name='bot_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='visitor',
            name='country_code',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='visitor',
            name='country_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='visitor',
            name='is_bot',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('pageview', 'Pageview'), ('click', 'Click'), ('page_exit', 'Page Exit'), ('scroll_depth', 'Scroll Depth'), ('engaged_visit', 'Engaged Visit'), ('cta_click', 'CTA Click'), ('custom', 'Custom')], max_length=32),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['project', 'event_name'], name='analytics_e_project_48184f_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['project', 'page_type'], name='analytics_e_project_2d2633_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['project', 'source_group'], name='analytics_e_project_641074_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingsession',
            index=models.Index(fields=['project', 'started_at', 'source_group'], name='analytics_t_project_f7798d_idx'),
        ),
        migrations.AddIndex(
            model_name='visitor',
            index=models.Index(fields=['project', 'country_code'], name='analytics_v_project_b6aa36_idx'),
        ),
        migrations.AddIndex(
            model_name='visitor',
            index=models.Index(fields=['project', 'is_bot'], name='analytics_v_project_da03b2_idx'),
        ),
    ]
